# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Card.create([
  { color: 'red', shape: 'diamond', shading: 'solid', number: 'one' },
  { color: 'red', shape: 'diamond', shading: 'solid', number: 'two' },
  { color: 'red', shape: 'diamond', shading: 'solid', number: 'three' },
  { color: 'red', shape: 'diamond', shading: 'empty', number: 'one' },
  { color: 'red', shape: 'diamond', shading: 'empty', number: 'two' },
  { color: 'red', shape: 'diamond', shading: 'empty', number: 'three' },
  { color: 'red', shape: 'diamond', shading: 'striped', number: 'one' },
  { color: 'red', shape: 'diamond', shading: 'striped', number: 'two' },
  { color: 'red', shape: 'diamond', shading: 'striped', number: 'three' },
  { color: 'red', shape: 'squiggle', shading: 'solid', number: 'one' },
  { color: 'red', shape: 'squiggle', shading: 'solid', number: 'two' },
  { color: 'red', shape: 'squiggle', shading: 'solid', number: 'three' },
  { color: 'red', shape: 'squiggle', shading: 'empty', number: 'one' },
  { color: 'red', shape: 'squiggle', shading: 'empty', number: 'two' },
  { color: 'red', shape: 'squiggle', shading: 'empty', number: 'three' },
  { color: 'red', shape: 'squiggle', shading: 'striped', number: 'one' },
  { color: 'red', shape: 'squiggle', shading: 'striped', number: 'two' },
  { color: 'red', shape: 'squiggle', shading: 'striped', number: 'three' },
  { color: 'red', shape: 'oval', shading: 'solid', number: 'one' },
  { color: 'red', shape: 'oval', shading: 'solid', number: 'two' },
  { color: 'red', shape: 'oval', shading: 'solid', number: 'three' },
  { color: 'red', shape: 'oval', shading: 'empty', number: 'one' },
  { color: 'red', shape: 'oval', shading: 'empty', number: 'two' },
  { color: 'red', shape: 'oval', shading: 'empty', number: 'three' },
  { color: 'red', shape: 'oval', shading: 'striped', number: 'one' },
  { color: 'red', shape: 'oval', shading: 'striped', number: 'two' },
  { color: 'red', shape: 'oval', shading: 'striped', number: 'three' },
  { color: 'green', shape: 'diamond', shading: 'solid', number: 'one' },
  { color: 'green', shape: 'diamond', shading: 'solid', number: 'two' },
  { color: 'green', shape: 'diamond', shading: 'solid', number: 'three' },
  { color: 'green', shape: 'diamond', shading: 'empty', number: 'one' },
  { color: 'green', shape: 'diamond', shading: 'empty', number: 'two' },
  { color: 'green', shape: 'diamond', shading: 'empty', number: 'three' },
  { color: 'green', shape: 'diamond', shading: 'striped', number: 'one' },
  { color: 'green', shape: 'diamond', shading: 'striped', number: 'two' },
  { color: 'green', shape: 'diamond', shading: 'striped', number: 'three' },
  { color: 'green', shape: 'squiggle', shading: 'solid', number: 'one' },
  { color: 'green', shape: 'squiggle', shading: 'solid', number: 'two' },
  { color: 'green', shape: 'squiggle', shading: 'solid', number: 'three' },
  { color: 'green', shape: 'squiggle', shading: 'empty', number: 'one' },
  { color: 'green', shape: 'squiggle', shading: 'empty', number: 'two' },
  { color: 'green', shape: 'squiggle', shading: 'empty', number: 'three' },
  { color: 'green', shape: 'squiggle', shading: 'striped', number: 'one' },
  { color: 'green', shape: 'squiggle', shading: 'striped', number: 'two' },
  { color: 'green', shape: 'squiggle', shading: 'striped', number: 'three' },
  { color: 'green', shape: 'oval', shading: 'solid', number: 'one' },
  { color: 'green', shape: 'oval', shading: 'solid', number: 'two' },
  { color: 'green', shape: 'oval', shading: 'solid', number: 'three' },
  { color: 'green', shape: 'oval', shading: 'empty', number: 'one' },
  { color: 'green', shape: 'oval', shading: 'empty', number: 'two' },
  { color: 'green', shape: 'oval', shading: 'empty', number: 'three' },
  { color: 'green', shape: 'oval', shading: 'striped', number: 'one' },
  { color: 'green', shape: 'oval', shading: 'striped', number: 'two' },
  { color: 'green', shape: 'oval', shading: 'striped', number: 'three' },
  { color: 'purple', shape: 'diamond', shading: 'solid', number: 'one' },
  { color: 'purple', shape: 'diamond', shading: 'solid', number: 'two' },
  { color: 'purple', shape: 'diamond', shading: 'solid', number: 'three' },
  { color: 'purple', shape: 'diamond', shading: 'empty', number: 'one' },
  { color: 'purple', shape: 'diamond', shading: 'empty', number: 'two' },
  { color: 'purple', shape: 'diamond', shading: 'empty', number: 'three' },
  { color: 'purple', shape: 'diamond', shading: 'striped', number: 'one' },
  { color: 'purple', shape: 'diamond', shading: 'striped', number: 'two' },
  { color: 'purple', shape: 'diamond', shading: 'striped', number: 'three' },
  { color: 'purple', shape: 'squiggle', shading: 'solid', number: 'one' },
  { color: 'purple', shape: 'squiggle', shading: 'solid', number: 'two' },
  { color: 'purple', shape: 'squiggle', shading: 'solid', number: 'three' },
  { color: 'purple', shape: 'squiggle', shading: 'empty', number: 'one' },
  { color: 'purple', shape: 'squiggle', shading: 'empty', number: 'two' },
  { color: 'purple', shape: 'squiggle', shading: 'empty', number: 'three' },
  { color: 'purple', shape: 'squiggle', shading: 'striped', number: 'one' },
  { color: 'purple', shape: 'squiggle', shading: 'striped', number: 'two' },
  { color: 'purple', shape: 'squiggle', shading: 'striped', number: 'three' },
  { color: 'purple', shape: 'oval', shading: 'solid', number: 'one' },
  { color: 'purple', shape: 'oval', shading: 'solid', number: 'two' },
  { color: 'purple', shape: 'oval', shading: 'solid', number: 'three' },
  { color: 'purple', shape: 'oval', shading: 'empty', number: 'one' },
  { color: 'purple', shape: 'oval', shading: 'empty', number: 'two' },
  { color: 'purple', shape: 'oval', shading: 'empty', number: 'three' },
  { color: 'purple', shape: 'oval', shading: 'striped', number: 'one' },
  { color: 'purple', shape: 'oval', shading: 'striped', number: 'two' },
  { color: 'purple', shape: 'oval', shading: 'striped', number: 'three' }
])
